module.exports = {
  MAX_RISK_PERCENT: 0.01,

  MAX_PORTFOLIO_EXPOSURE: 0.30,

  MAX_DRAWDOWN: 0.15,

  HIGH_VOLATILITY_THRESHOLD: 5,

  BASE_RISK_REWARD: 2,

  MIN_CONFIDENCE: 60,

  MAX_POSITION_SIZE_MULTIPLIER: 1.5,

  MIN_POSITION_SIZE_MULTIPLIER: 0.5,
};
