"use strict";

module.exports = Object.freeze({

  ROLES: Object.freeze({
    OWNER: "OWNER",
    ADMIN: "ADMIN",
    SYSTEM: "SYSTEM",
    AI_ENGINE: "AI_ENGINE",
    WORKER: "WORKER",
    READ_ONLY: "READ_ONLY"
  }),

  TOKEN_TYPES: Object.freeze({
    ACCESS: "ACCESS",
    REFRESH: "REFRESH"
  }),

  SESSION_STATUS: Object.freeze({
    ACTIVE: "ACTIVE",
    EXPIRED: "EXPIRED",
    REVOKED: "REVOKED",
    LOCKED: "LOCKED"
  }),

  MFA_STATUS: Object.freeze({
    DISABLED: "DISABLED",
    PENDING: "PENDING",
    ENABLED: "ENABLED"
  }),

  AUDIT_ACTIONS: Object.freeze({
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    PASSWORD_CHANGED: "PASSWORD_CHANGED",
    PASSWORD_RESET: "PASSWORD_RESET",
    MFA_ENABLED: "MFA_ENABLED",
    MFA_DISABLED: "MFA_DISABLED",
    TOKEN_ISSUED: "TOKEN_ISSUED",
    TOKEN_REFRESHED: "TOKEN_REFRESHED",
    TOKEN_REVOKED: "TOKEN_REVOKED",
    SESSION_CREATED: "SESSION_CREATED",
    SESSION_REVOKED: "SESSION_REVOKED",
    EMERGENCY_STOP: "EMERGENCY_STOP",
    CONFIGURATION_CHANGED: "CONFIGURATION_CHANGED"
  }),

  LOGIN_RESULT: Object.freeze({
    SUCCESS: "SUCCESS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
    MFA_REQUIRED: "MFA_REQUIRED",
    MFA_FAILED: "MFA_FAILED",
    SESSION_EXPIRED: "SESSION_EXPIRED"
  })

});
