"use strict";

module.exports = Object.freeze({
  // Authentication
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_EXPIRED: "ACCOUNT_EXPIRED",

  // Authorization
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  ROLE_REQUIRED: "ROLE_REQUIRED",
  INSUFFICIENT_PRIVILEGES: "INSUFFICIENT_PRIVILEGES",

  // Session
  SESSION_ERROR: "SESSION_ERROR",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_REVOKED: "SESSION_REVOKED",
  SESSION_INVALID: "SESSION_INVALID",

  // Token
  TOKEN_ERROR: "TOKEN_ERROR",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  TOKEN_SIGNATURE_INVALID: "TOKEN_SIGNATURE_INVALID",

  // MFA
  MFA_ERROR: "MFA_ERROR",
  MFA_REQUIRED: "MFA_REQUIRED",
  MFA_INVALID_CODE: "MFA_INVALID_CODE",
  MFA_BACKUP_CODE_INVALID: "MFA_BACKUP_CODE_INVALID",
  MFA_SETUP_REQUIRED: "MFA_SETUP_REQUIRED",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",

  // Security
  SECURITY_VIOLATION: "SECURITY_VIOLATION",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  SUSPICIOUS_ACTIVITY: "SUSPICIOUS_ACTIVITY",
  IP_BLOCKED: "IP_BLOCKED",

  // API
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE"
});
